eureka:
  instance:
    hostname: provider_8001
    instance-id: localhost_provider_8001
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka